[[headers]]
    for = "/static/*.woff"
    [headers.values]
        Cache-Control = "public, max-age=604800"

[[headers]]
    for = "/static/*.woff2"
    [headers.values]
        Cache-Control = "public, max-age=604800"